[package]
name = "ps4-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5"
serde = { version = "1.0", features = ["derive"] }
serde-pickle = "1.0"
edit-distance = "2.1.0"
csv = "1.1.6"
